# .github/workflows/weekly-update.yml

name: Weekly Update

on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install deps
        run: npm ci

      - name: Run Cypress tests
        uses: cypress-io/github-action@v5
        with:
          spec: cypress/scrape.cy.js
          browser: electron
          record: false

      - name: Post‑process & commit
        run: |
          npm run postprocess
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/NewData.jsx data/applications.json
          if ! git diff --cached --quiet; then
            git commit -m "chore: weekly data update $(date -u +'%Y-%m-%d')"
            git push
          else
            echo "No changes to commit"
          fi
