# .github/workflows/cypress-weekly.yml

name: Weekly Cypress Run and Push

on:
  schedule:
    - cron: '0 0 * * 0'   # Sundays at 00:00 UTC
  workflow_dispatch:

# 👇 Request write access for the GITHUB_TOKEN
permissions:
  contents: write

jobs:
  cypress_run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0           # safer for pushes/tags
          token: ${{ secrets.GITHUB_TOKEN }}  # explicit (default, but be clear)

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Run Cypress Tests
        run: npm run scrape
        continue-on-error: true
        env:
          CYPRESS_PAGE_LOAD_TIMEOUT: 120000

      - name: Check for Changes
        id: git_status
        shell: bash
        run: |
          STATUS="$(git status --porcelain)"
          # new way to set step outputs:
          echo "status<<EOF" >> "$GITHUB_OUTPUT"
          echo "$STATUS" >> "$GITHUB_OUTPUT"
          echo "EOF" >> "$GITHUB_OUTPUT"

      - name: Configure Git (only if changes)
        if: steps.git_status.outputs.status != ''
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          # ensure pushes use the token:
          git remote set-url origin "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"

      - name: Commit and Push Changes
        if: steps.git_status.outputs.status != ''
        run: |
          git add -A
          git commit -m "Automated Cypress run results [skip ci]" || echo "No changes to commit."
          # push back to the same branch this workflow runs on:
          git push origin HEAD:${{ github.ref_name }}
