# .github/workflows/cypress-weekly.yml
name: Weekly Cypress Run and Push

on:
  schedule:
    - cron: '0 0 * * 0'   # Sundays at 00:00 UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  preflight:
    name: Preflight network checks
    runs-on: ubuntu-latest
    env:
      NODE_VERSION: '20'
      NODE_OPTIONS: --dns-result-order=ipv4first
    steps:
      - uses: actions/checkout@v4

      - name: Print runner egress IPs
        run: |
          echo "Public IPv4: $(curl -4 -s https://ifconfig.me || true)"
          echo "Public IPv6: $(curl -6 -s https://ifconfig.me || true)"

      - name: DNS reachability
        run: |
          set -x
          getent hosts citydev-portal.edinburgh.gov.uk || true
          nslookup citydev-portal.edinburgh.gov.uk || true

      - name: TLS/HTTP reachability (IPv4, real UA)
        run: |
          set -x
          mkdir -p logs
          curl --ipv4 \
               -A "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126 Safari/537.36" \
               -I -L -v "https://citydev-portal.edinburgh.gov.uk/idoxpa-web/search.do?action=advanced" \
               -o /dev/null 2> logs/curl_verbose.txt
        # If curl exits non-zero, we want the job to fail.
      
      - name: Upload curl trace
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: preflight-logs
          path: logs/curl_verbose.txt

  cypress_run:
    name: Run Cypress and push results
    runs-on: ubuntu-latest
    needs: preflight   # only run if preflight succeeded
    env:
      NODE_OPTIONS: --dns-result-order=ipv4first
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Run Cypress Tests
        run: npm run scrape
        env:
          CYPRESS_PAGE_LOAD_TIMEOUT: 120000

      - name: Upload Cypress artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-artifacts
          path: |
            cypress/screenshots
            cypress/videos
            cypress/logs

      - name: Check for Changes
        id: git_status
        shell: bash
        run: |
          STATUS="$(git status --porcelain)"
          echo "status<<EOF" >> "$GITHUB_OUTPUT"
          echo "$STATUS" >> "$GITHUB_OUTPUT"
          echo "EOF" >> "$GITHUB_OUTPUT"

      - name: Configure Git (only if changes)
        if: steps.git_status.outputs.status != ''
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git remote set-url origin "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"

      - name: Commit and Push Changes
        if: steps.git_status.outputs.status != ''
        run: |
          git add -A
          git commit -m "Automated Cypress run results [skip ci]" || echo "No changes to commit."
          git push origin HEAD:${{ github.ref_name }}
