name: Weekly Update

on:
  schedule:
    - cron: '0 0 * * 0'    # every Sunday at midnight UTC
  workflow_dispatch:

# allow the checkout step to push back
permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      # 1) checkout makes GITHUB_TOKEN available for pushes
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          persist-credentials: true

      # 2) setup Node (v2 is fine if you prefer)
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      # 3) install & run inside the cypress folder, just like before
      - name: Install & run scraper
        run: |
          cd cypress
          npm ci
          npm run search-and-save
          cd ..

      # 4) commit & push everything (including data/NewData.jsx, etc.)
      - name: Commit and push changes
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git diff --quiet --cached || git commit -m "chore: weekly data push $(date -u +'%Y-%m-%d')"
          git push
