# .github/workflows/cypress-weekly.yml

name: Weekly Cypress Run and Push

on:
  schedule:
    - cron: '0 0 * * 0'   # Sundays at 00:00 UTC
  workflow_dispatch:

# 👇 Request write access for the GITHUB_TOKEN
permissions:
  contents: write


  # .github/workflows/scrape.yml  (snippet)
jobs:
  scrape:
    runs-on: ubuntu-latest
    env:
      NODE_VERSION: '20'
      # Force Node/Cypress to prefer IPv4 in case IPv6 path is broken
      NODE_OPTIONS: --dns-result-order=ipv4first
    steps:
      - uses: actions/checkout@v4

      - name: Print runner IPs (egress debug)
        run: |
          echo "Public IPv4:" $(curl -4 -s https://ifconfig.me || true)
          echo "Public IPv6:" $(curl -6 -s https://ifconfig.me || true)

      - name: DNS + TLS reachability for target host
        run: |
          set -x
          nslookup citydev-portal.edinburgh.gov.uk || true
          # Try IPv4 with a real browser UA and show full TLS/HTTP trace
          curl --ipv4 -A "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126 Safari/537.36" \
               -I -L -v https://citydev-portal.edinburgh.gov.uk/idoxpa-web/search.do?action=advanced || exit 2

      - name: Save curl trace
        if: failure()
        run: echo "Curl failed above; likely IP/geo/UA block or TLS path issue."


  cypress_run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0           # safer for pushes/tags
          token: ${{ secrets.GITHUB_TOKEN }}  # explicit (default, but be clear)

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Run Cypress Tests
        run: npm run scrape
        continue-on-error: true
        env:
          CYPRESS_PAGE_LOAD_TIMEOUT: 120000

      - name: Check for Changes
        id: git_status
        shell: bash
        run: |
          STATUS="$(git status --porcelain)"
          # new way to set step outputs:
          echo "status<<EOF" >> "$GITHUB_OUTPUT"
          echo "$STATUS" >> "$GITHUB_OUTPUT"
          echo "EOF" >> "$GITHUB_OUTPUT"

      - name: Configure Git (only if changes)
        if: steps.git_status.outputs.status != ''
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          # ensure pushes use the token:
          git remote set-url origin "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"

      - name: Commit and Push Changes
        if: steps.git_status.outputs.status != ''
        run: |
          git add -A
          git commit -m "Automated Cypress run results [skip ci]" || echo "No changes to commit."
          # push back to the same branch this workflow runs on:
          git push origin HEAD:${{ github.ref_name }}
